spring:
  application:
    name: BankingApplication
  datasource:
    url: jdbc:postgresql://172.27.239.227:5432/banking
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: 172.27.239.227
      port: 6379
  profiles:
    active: prod
rsa:
  public-key-location: security/public.key
  private-key-location: security/private.key
token:
  expiration: 600000
snow-flake:
  node-id: 21
server:
  servlet:
    context-path: /api
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    display-request-duration: true
    disable-swagger-default-url: true
  api-docs:
    enabled: true
    path: /v3/api-docs