spring:
  application:
    name: BankingApplication
  datasource:
    url: jdbc:postgresql://postgres:5432/banking
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  elasticsearch:
    password: elastic
    username: elastic
    uris: http://elasticsearch:9200
  data:
    redis:
      host: redis
      port: 6379
  profiles:
    active: prod
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topic:
      auth-logs: auth-logs
      transfer-logs: transfer-logs
rsa:
  public-key-location: security/public.key
  private-key-location: security/private.key
token:
  expiration: 600000
snow-flake:
  node-id: 21
server:
  servlet:
    context-path: /api
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    display-request-duration: true
    disable-swagger-default-url: true
  api-docs:
    enabled: true
    path: /v3/api-docs